export const TEAM_MAP = {
  IND_M: { label: "India Men", apiName: "India" },
  IND_W: { label: "India Women", apiName: "India Women" },
  AUS_M: { label: "Australia Men", apiName: "Australia" },
  AUS_W: { label: "Australia Women", apiName: "Australia Women" },
  ENG_M: { label: "England Men", apiName: "England" },
  ENG_W: { label: "England Women", apiName: "England Women" },
  NZ_M: { label: "New Zealand Men", apiName: "New Zealand" },
  NZ_W: { label: "New Zealand Women", apiName: "New Zealand Women" },
  SA_M: { label: "South Africa Men", apiName: "South Africa" },
  SA_W: { label: "South Africa Women", apiName: "South Africa Women" },
  PAK_M: { label: "Pakistan Men", apiName: "Pakistan" },
  PAK_W: { label: "Pakistan Women", apiName: "Pakistan Women" },
  SL_M: { label: "Sri Lanka Men", apiName: "Sri Lanka" },
  WI_M: { label: "West Indies Men", apiName: "West Indies" },
  BAN_M: { label: "Bangladesh Men", apiName: "Bangladesh" },
  AFG_M: { label: "Afghanistan Men", apiName: "Afghanistan" },
  ZIM_M: { label: "Zimbabwe Men", apiName: "Zimbabwe" },
  IRE_M: { label: "Ireland Men", apiName: "Ireland" },
};
